name = "nanofase"
version = "0.0.4"
license = "BSD-3-Clause"
author = "Sam Harrison"
maintainer = "sharrison@ceh.ac.uk"
copyright = "Copyright 2023, UKCEH"

[dependencies]
feh.git = "https://github.com/samharrison7/fortran-error-handler"
spoof.git = "https://github.com/samharrison7/spoof"
datetime.path = "vendor/datetime-fortran"
mo_netcdf.path = "vendor/mo_netcdf"
bmif = { git = "https://github.com/samharrison7/bmi-fortran", branch="fpm-support" }

[build]
auto-executables = false

[[executable]]
name = "nanofase"
source-dir = "src"
main = "main.f90"

[[executable]]
name = "bmi_nanofase"
source-dir = "src"
main = "bmi_main.f90"