package:
  name: nanofase
  version: 0.0.4

source:
  path: ..

build:
  script: fpm @install --prefix=${PREFIX}

requirements:
  build:
    - gcc
    - gfortran
    - gxx
    - netcdf-fortran
    - fpm
  run:
    - libgcc
    - libgfortran
    - netcdf-fortran

about:
  home: https://nerc-ceh.github.io/nanofase
  license: BSD 3 Clause
  summary: Nanomaterial exposure in the environment
  description: |
    NanoFASE is a multimedia spatiotemporal model of nanomaterial
    fate and exposure in the environment.
  dev_url: https://github.com/nerc-ceh/nanofase
  doc_url: https://nerc-ceh.github.io/nanofase